### ISSUE TITLE
import ITR give type error on PC

### ISSUE THREAD

**Issue by saurabhaviva** [os-climate/ITR#185]
**The ITR package has some issues when i try to import ITR get class error
did someone experience the same issue ? any solutions ?**

```
>>> import ITR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\A203098\AppData\Roaming\Python\Python38\site-packages\ITR\__init__.py", line 5, in <module>
    from .data import osc_units
  File "C:\Users\A203098\AppData\Roaming\Python\Python38\site-packages\ITR\data\__init__.py", line 6, in <module>
    from .data_providers import CompanyDataProvider
  File "C:\Users\A203098\AppData\Roaming\Python\Python38\site-packages\ITR\data\data_providers.py", line 7, in <module>
    from ITR.configs import TabsConfig, ColumnsConfig, VariablesConfig, TemperatureScoreConfig
  File "C:\Users\A203098\AppData\Roaming\Python\Python38\site-packages\ITR\configs.py", line 7, in <module>
    from .interfaces import TemperatureScoreControls
  File "C:\Users\A203098\AppData\Roaming\Python\Python38\site-packages\ITR\interfaces.py", line 200, in <module>
    class AggregationContribution(PintModel):
  File "C:\Users\A203098\AppData\Roaming\Python\Python38\site-packages\ITR\interfaces.py", line 203, in AggregationContribution
    temperature_score: Quantity['delta_degC']
  File "C:\Program Files (x86)\Python38-32\lib\typing.py", line 261, in inner
    return func(*args, **kwds)
  File "C:\Program Files (x86)\Python38-32\lib\typing.py", line 897, in __class_getitem__
    _check_generic(cls, params)
  File "C:\Users\A203098\AppData\Roaming\Python\Python38\site-packages\typing_extensions.py", line 100, in _check_generic
    raise TypeError(f"{cls} is not a generic class")
TypeError: <class 'pint.util.Quantity'> is not a generic class
```

**Comment by saurabhaviva** [comment]
hi, is there any solution to above?

**Comment by HeatherAck** [comment]
adding @MichaelTiemannOSC as he implemented pint

**Comment by MichaelTiemannOSC** [comment]
Apologies...just seeing this now as I step away from my keyboard.  Can we discuss in the call set for tomorrow 6AM ET?

**Comment by MichaelTiemannOSC** [comment]
OK!  A few things...

First, when we walked through the installation instructions, we forgot to activate the `itr_ui` environment:

```
itr_ui\Scripts\activate
```

The itr_ui environment may have been created in ITR-develop, not ITR-develop/examples.  I'm not sure that's a real problem by itself, but you may want to move it and/or remove it and re-do it.  With that env activated, the install -r requirements.txt command should install the correct versions of what's needed.  But it's missing `multiprocess`, so you need to run:

```
pip install multiprocess
```

And the big one: from ITR-develop, run

```
pip install -e .
```

That installs the correct ITR library, not the one from PyPi.

Finally, I put some more data checks into the tool and neglected to update the sample data (which has the error that the target start year and target end year for company ID US29364G1031 are the same (the end year must be greater).  I'll update the test file and push the change upstream.  But you can manually change the target start year to 2020 or some such.

I can hop back on a call if you need more help.

**Comment by kervella-claude-jean** [comment]
Hello
The double quote (") is missing at the end of sphinx-autodoc-typehints in setup.py in install_requires section on main branch
Regards

**Comment by MichaelTiemannOSC** [comment]
Thanks for the heads up.  Will get to it ASAP.

**Comment by MichaelTiemannOSC** [comment]
Alas there is a dependency vulnerability from the package numexpr, imported by pandas, that's preventing me from pushing a new release through the CI/CD system.  I have left a comment in the issue for the `numexpr` people and as soon as that is resolved, we'll push a new release.  In the mean time, please apply your patch locally.

**Comment by MichaelTiemannOSC** [comment]
A new version 1.0.5 is now up on PyPi.  It has this fix and a number of others (including compatibility with the newly release Pandas 2.1.0 library).
